// packages/solid/src/context/SiloProvider.ts
import { createComponent, createMemo } from "solid-js";
import type { ParentProps } from "solid-js";
import { SiloContext } from "src/context/SiloContext";
import type { RegisteredSilo } from "src/types/Register";

/** Provider inputs. @example `const props = { silo, scope: "account" } satisfies SiloProviderProps;` */
export type SiloProviderProps = ParentProps<{
  silo: RegisteredSilo;
  scope?: string | undefined;
}>;

/**
 * Provides an application-owned Silo and follows reactive scope changes.
 * @example `<SiloProvider silo={silo} scope={account()}><Settings /></SiloProvider>`
 */
export const SiloProvider = (props: SiloProviderProps) => {
  const silo = createMemo(() => props.silo);
  const scope = createMemo(() =>
    props.scope === undefined ? silo() : silo().scope(props.scope),
  );
  return createComponent(SiloContext.Provider, {
    value: { silo, scope },
    get children() {
      return props.children;
    },
  });
};

// packages/svelte/src/context/SiloProvider.svelte
<!--
@component Provides an application-owned Silo and a reactive scope.
@example `<SiloProvider {silo} scope={account}><Settings /></SiloProvider>`
-->
<script lang="ts">
  import { setContext } from "svelte";
  import { SILO_CONTEXT } from "./SiloContext.js";
  import type { SiloContextValue } from "./SiloContext.js";
  import type { SiloProviderProps } from "../types/SiloProviderProps.js";

  const props: SiloProviderProps = $props();
  const scope = $derived(
    props.scope === undefined ? props.silo : props.silo.scope(props.scope),
  );
  setContext(SILO_CONTEXT, {
    silo: {
      get current() {
        return props.silo;
      },
    },
    scope: {
      get current() {
        return scope;
      },
    },
  } satisfies SiloContextValue);
</script>

{#if props.children}
  {@render props.children()}
{/if}
