// packages/solid/src/primitives/useValueStatus.ts
import { useContext } from "solid-js";
import type { Accessor } from "solid-js";
import type { SiloValue, ValueStatus } from "@priemskiyyy/silo";
import { useObservableValue } from "src/primitives/internal/useObservableValue";
import { SiloContext } from "src/context/SiloContext";
import type { RegisteredKey } from "src/types/Register";

/** Observes status without subscribing to value snapshots. @example `const status = useValueStatus("theme");` */
export const useValueStatus = (
  source:
    | RegisteredKey
    | Pick<SiloValue<unknown>, "status">
    | Accessor<RegisteredKey | Pick<SiloValue<unknown>, "status">>,
  onChange?: (status: ValueStatus) => void | Promise<unknown>,
) => {
  const context = useContext(SiloContext);
  return useObservableValue(() => {
    const current = typeof source === "function" ? source() : source;
    if (current === undefined || current === null) {
      throw new Error("A Silo value handle or key is required.");
    }
    if (typeof current !== "string") {
      return current.status;
    }
    if (context === undefined) {
      throw new Error("Silo primitives must be used within a SiloProvider.");
    }
    return context.scope().value(current).status;
  }, onChange);
};

// packages/react/src/hooks/useValueStatus.ts
import { useContext, useMemo } from "react";
import type { SiloValue, ValueStatus } from "@priemskiyyy/silo";
import { useObservableValue } from "src/hooks/internal/useObservableValue";
import { SiloContext } from "src/context/SiloContext";
import type { RegisteredKey } from "src/types/Register";

// Interned so every call hands React the same reference, the way the core
// interns the statuses its own stores dedupe on.
const HYDRATING_VALUE_STATUS = { state: "hydrating" } satisfies ValueStatus;

const getServerValueStatus = () => HYDRATING_VALUE_STATUS;

/**
 * Observes one value's progress without reading the value. Nothing here
 * subscribes to the snapshot, so a component that only watches status does not
 * rerender when the value changes, and `error.phase` says which side failed.
 *
 * @example
 * ```ts
 * const status = useValueStatus("user");
 *
 * if (status.state === "hydrating") return <Spinner />;
 * ```
 */
export const useValueStatus = (
  source: RegisteredKey | Pick<SiloValue<unknown>, "status">,
  onChange?: (status: ValueStatus) => void | Promise<unknown>,
) => {
  const context = useContext(SiloContext);
  const status = useMemo(() => {
    if (source === undefined || source === null) {
      throw new Error("A Silo value handle or key is required.");
    }
    if (typeof source !== "string") {
      return source.status;
    }
    if (context === undefined) {
      throw new Error("Silo hooks must be used within a SiloProvider.");
    }
    return context.scope.value(source).status;
  }, [context, source]);
  return useObservableValue(status, getServerValueStatus, onChange);
};
